update_fastlane

default_platform(:ios)

platform :ios do

  before_all do
    cocoapods
    increment_build_number
    #gym(scheme: "TeamCityTest", workspace: "TeamCityTest.xcworkspace")
  end

  lane :custom_lane do

  end

  lane :test do
    scan(device: "iPhone 8")
  end

  after_all do |lane|

  end

  error do |lane, exception|
    print "error in lane! "
  end

end